### ISSUE TITLE
Let's Review this Repo

### ISSUE THREAD

**Issue by sadafie** [meetup/meetup-web-components#1]
I still have the following things to iron out, but this issue for this repo will go in conjuction with [PR #342](https://github.com/meetup/mup-web/pull/342) in `mup-web`. 

## TODO
- [x] Rename repo
- [ ] Get storybook working  ( Issue #3 )
- [ ] Get svg icons working ( Issue #5 )
- [x] Get tests working
- [x] Get generate component script working
- [x] Make sure eslint works
- [x] Update README
- [x] Fix file casing
- [x] rename tearsheet to display date

## Open Questions
- [x] What should we rename this repo to? **==> `meetup-web-components`**
- [x] Do we want jsdoc here? **==> No**
- [ ] Test cases have a dependency on `meetup-web-platform` for mock api data. I keep going back and forth on this dependency.. see the pro and cons. Thoughts?

## Follow ups
- [ ] Create a public npm pkg ( Issue #6 )
- [ ] Semantic versioning ( Issue #6 )
- [ ] Setup coverage reporting ( Issue # 7)

**Comment by sadafie** [comment]
Filed individual issues for each unfinished TODO in this Issue. Going to close.
